[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
traz_log = "13p4xV6WHaPwWzno1F6Z6MeY9b9wLYtEMAnUF8ofdW75"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
